title:
  en: Daniil Khrestianovskii
  ru: Хрестьяновский Даниил

logo: "/images/picture.png?raw=true"

description:
  en: >-
    <p align="center">
    Saint Petersburg, Russia
    <br> Telegram @dankhrestyan
    <br> khrestyanovskii@gmail.com
    <br> <a href="resume/CV_Khrestianovskii_Daniil.pdf">Resume</a> |
    <a href="https://github.com/casualdoto">GitHub</a>
    </p>
    
    <p align="justify">
    I am a <b>backend developer and data analyst</b> who loves learning new things and implementing ideas.
    <br><br>
    I am studying in the <b>Master’s program in Software Engineering (09.04.04) at Ural Federal University</b>, 2026–2028.
    <br><br>
    Bachelor’s program at <b>Peter the Great St. Petersburg Polytechnic University</b>, 2022–2026: <b>Mathematical Software and Information Systems Administration (02.03.03)</b>.
    <br><br>
    </p>

  ru: >-
    <p align="center">
    Санкт-Петербург, Россия
    <br> Telegram @dankhrestyan
    <br> khrestyanovskii@gmail.com
    <br> <a href="resume/CV_Хрестьяновский_Даниил.pdf">Резюме</a> |
    <a href="https://github.com/casualdoto">GitHub</a>
    </p>
    
    <p align="justify">
    Я <b>бэкенд разработчик и аналитик данных</b>, который любит изучать новое и реализовывать идеи.
    <br><br>
    Я учусь в <b>магистратуре Уральского федерального университета (УрФУ)</b> по направлению <b>«Программная инженерия» (09.04.04)</b>, 2026–2028.
    <br><br>
    Бакалавриат в <b>Санкт-Петербургском политехническом университете Петра Великого</b>, 2022–2026: <b>«Математическое обеспечение и администрирование информационных систем» (02.03.03)</b>.
    <br><br>
    </p>
  
theme: jekyll-theme-minimal
google_analytics: G-8LG4JT55GW # Google Analytics tracking ID

# Настройки языка по умолчанию
default_lang: "ru"
languages: ["ru", "en"]


